pycha_pl/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import logout

from pycha import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),

    url(r'^restaurateur/$', views.RestaurateurView.as_view()),
    url(r'^restaurateur/add$', views.RestaurateurProcessView.as_view()),
    url(r'^restaurateur/add/new$', views.RestaurateurProcessView.as_view()),

    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^register/$', views.Register.as_view(), name='register'),

    url(r'^restaurants/$', views.RestaurantsView.as_view(), name='restaurants'),
    url(r'^restaurants/(?P<restaurant_id>[0-9]+)$', views.RestaurantDetails.as_view(), name='restaurant details'),

    url(r'^restaurants/json/$', views.RestaurantsProcessView.as_view(), name='get restaurants'),
    url(r'restaurants/json/(?P<restaurant_id>[0-9]+)/$', views.DishesProcessView.as_view(), name='get dishes'),

    url(r'^cart/$', views.CartView.as_view(), name='cart'),
    url(r'^cart/add_dish/(?P<dish_id>[0-9]+)/$', views.DishesProcessView.as_view(), name='add dish to cart'),


    url(r'^cart/json/$', views.CartProcessView.as_view(), name='get cart'),
    url(r'^cart/remove_dish/(?P<quantity_dish_id>[0-9]+)/(?P<order_id>[0-9]+)/$', views.CartProcessView.as_view(),
        name='remove dish from cart'),

    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/update/$', views.ProfileView.as_view(), name='profile update'),
    url(r'^profile/update/address/$', views.ProfileView.as_view(), name='address update'),
    url(r'^profile/client/address/$', views.ProfileProcessView.as_view(), name='client address'),

    url(r'^upload/$', views.UploadView.as_view())
]

pycha/models.py
from django.contrib.auth.models import User
from django.db import models


class Client(models.Model):
    def __str__(self):
        return 'Client: {}'.format(self.user)

    user = models.ForeignKey(User)
    is_taster = models.BooleanField()


class Address(models.Model):
    def __str__(self):
        return 'Address: {} {}'.format(self.street, self.doors)

    country = models.CharField(max_length=15, blank=True, default='Polska')
    city = models.CharField(max_length=30, blank=True, default='Wrocław')
    post_code = models.CharField(max_length=6)
    street = models.CharField(max_length=20)
    doors = models.PositiveSmallIntegerField()
    client = models.ForeignKey(Client, on_delete=models.CASCADE, blank=True, null=True)
    info = models.CharField(max_length=45, blank=True, null=True)


class Order(models.Model):
    def __str__(self):
        return 'Order of : {}'.format(self.client.user)

    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.PROTECT)
    total_price = models.DecimalField(max_digits=7, decimal_places=2)
    date = models.DateTimeField()


class Restaurateur(models.Model):
    def __str__(self):
        return 'Restaurateur: {}#{}'.format(self.user.username, self.id)

    user = models.ForeignKey(User)
    bank_account = models.CharField(max_length=20)
    phone = models.CharField(max_length=9)
    balance = models.DecimalField(max_digits=7, decimal_places=2)


class Restaurant(models.Model):
    def __str__(self):
        return 'Restaurant: {}'.format(self.name)

    restaurateur = models.ForeignKey(Restaurateur, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.PROTECT)
    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=9)
    delivery_radius = models.PositiveSmallIntegerField()
    description = models.CharField(max_length=700)


class Opinion(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    weight = models.FloatField()
    contents = models.CharField(max_length=300)
    date = models.DateTimeField()


class Parameter(models.Model):
    def __str__(self):
        return 'Parameter: #{} {}'.format(self.type, self.name)

    name = models.CharField(max_length=30)
    type = models.PositiveSmallIntegerField()


class Dish(models.Model):
    def __str__(self):
        return 'Dish: {}'.format(self.name)

    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    name = models.CharField(max_length=45)
    type = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    description = models.CharField(max_length=100, blank=True, null=True)
    parameters = models.ManyToManyField(Parameter)


class QuantityDish(models.Model):
    def __str__(self):
        return '{} {} {}'.format(self.dish.name, self.parameter, self.quantity)

    order = models.ForeignKey(Order)
    dish = models.ForeignKey(Dish)
    quantity = models.PositiveSmallIntegerField()
    parameter = models.ForeignKey(Parameter)


class Suborder(models.Model):
    def __str__(self):
        return 'Suborder of : {}'.format(self.order)

    order = models.ForeignKey(Order)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    is_realised = models.BooleanField()
    dishes_quantities = models.ManyToManyField(QuantityDish)


class Message(models.Model):
    sender = models.ForeignKey(User, related_name='sender_of_the_message')
    recipient = models.ForeignKey(User, blank=True, null=True, related_name='recipient_of_the_message')
    contents = models.CharField(max_length=300)
    date = models.DateTimeField()

templates/restaurant/details.html
{% extends 'base.html' %}

{% block libs %}
    {% load staticfiles %}
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
    <script src="{% static 'js/utils.js' %}"></script>
    <script src="{% static 'js/restaurant.js' %}"></script>

{% endblock %}

{% block content_name %}{% endblock %}

{% block content %}

    <div class="panel panel-default">
        <div class="panel-heading"><h4>{{ restaurant.name }} - szczegóły</h4></div>

        <div class="thumbnail">
            <img src="/static/images/restaurants/{{ restaurant.pk }}.jpg" style="padding: 10px; max-height: 450px;">
        </div>


        <div class="panel-body">
            <h3 style="margin-left: 2%">O restauracji:</h3>
            <div class="row">
                <div class="col-sm-6">
                    <span class="panel-list-element"><b>Opis</b>:<br> {{ restaurant.description }}</span>
                </div>
                <div class="col-sm-3">

                    <span class="panel-list-element"><b>Adres:</b></span>
                    <span class="panel-list-element">ul.{{ restaurant.address.street }} {{ restaurant.address.doors }}</span>
                    <span class="panel-list-element">{{ restaurant.address.city }}</span>
                    <span class="panel-list-element"><b>Telefon</b>: {{ restaurant.phone }}</span>
                    <span class="panel-list-element"><b>Promień dowozu</b>: {{ restaurant.delivery_radius }}</span>
                    <span class="panel-list-element"><b>Właściciel</b>: {{ restaurant.restaurateur.user.first_name }} {{ restaurant.restaurateur.user.last_name }}</span>
                </div>
                <div class="col-sm-2">
                    <img src="https://d30y9cdsu7xlg0.cloudfront.net/png/98458-200.png">
                </div>

            </div>
        </div>
    </div>

    <div ng-app="restaurant" ng-controller="detailsCtrl" ng-init="getDishes({{ restaurant.id }})">

        <div class="panel panel-default">
            <div class="panel-heading"><h4>Oferowane dania</h4></div>

            <div class="panel-body">

                <div class="row" style="margin-bottom: 10px;">
                    <div class="col-sm-12"><b>Sortuj według:</b></div>
                    <div class="col-sm-2">
                        <select ng-model="mySortType" ng-options="type.text for type in sortTypes"
                                class="form-control"></select>
                    </div>

                    <div class="col-sm-7"></div>

                    <div class="input-group" style="margin-right: 10px;">
                        <span class="input-group-addon"><i class=" glyphicon glyphicon-search"></i></span>
                        <input ng-model="search.name" placeholder="Nazwa dania" class="form-control">
                    </div>
                </div>

                <div ng-repeat="dish in dishes | filter: search | orderBy: mySortType.value">
                    <div class="col-sm-4">
                        <div class="panel panel-default">
                            <div style="padding: 20px;">
                                <span class="dishesHeader" style="font-size: 20px;">{$ dish.name $}</span>
                                {$ dish.description $}
                                <span class="dishesHeader" style="display: inline"><br>Cena: </span>{$ dish.price $} zł
                                <span class="dishesHeader">Do wyboru:</span>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <select ng-model="dish.chosenParam"
                                                ng-options="parameter.name for parameter in dish.parameters"
                                                class="form-control"></select>
                                    </div>
                                </div>

                                <button id="dish{$ dish.id $}" ng-click="addDishToCart(dish.id, dish.chosenParam)" class="btn btn-primary btn-xs" style="margin-top: 10px;">
                                    Dodaj danie <span class="glyphicon glyphicon-plus"></span>
                                </button>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

{% block includes %}
    {% include 'modals/defaultModal.html' %}
    {% include 'modals/errorModal.html' %}
{% endblock %}

templates/restaurant/restaurants.html
{% extends 'base.html' %}

{% block libs %}
    {% load staticfiles %}
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
    <script src="{% static 'js/utils.js' %}"></script>
    <script src="{% static 'js/restaurant.js' %}"></script>

    <script>
        $(document).ready(function () {
            $('#restaurantsNav').addClass('active')
        });
    </script>
{% endblock %}

{% block content_name %}Restauracje{% endblock %}

{% block content %}

    <div ng-app="restaurant" ng-controller="restaurantCtrl" ng-init="getRestaurants()">

        <div class="col-sm-12"><b>Sortuj według:</b></div>
        <div class="col-sm-2">
            <select ng-model="mySortType" ng-options="type.text for type in sortTypes" class="form-control"></select>
        </div>
        <div class="col-sm-6"></div>

        <div class="input-group" style="margin-bottom: 20px;">
            <span class="input-group-addon"><i class=" glyphicon glyphicon-search"></i></span>
            <input id="filter" ng-model="search.name" placeholder="Nazwa restauracji" class="form-control">
        </div>


        <div ng-repeat="restaurant in restaurants | filter: search | orderBy: mySortType.value">
            <a ng-href="{$ restaurant.detailsUrl $}">
                <div class="col-sm-4">

                    <div class="panel panel-default" id="id_restaurant">
                        <div id="restaurant-{$ restaurant.id $}" class="panel-heading"><h4>{$ restaurant.name $}</h4></div>
                        <div class="thumbnail">
                            <img ng-src="{$ restaurant.url $}" style="padding: 10px; max-height: 200px">
                        </div>

                        <span class="panel-list-element"><b>Adres:</b></span>
                        <span class="panel-list-element">ul.{$ restaurant.street $} {$ restaurant.doors $}</span>
                        <span class="panel-list-element">{$ restaurant.city $}</span>
                        <span class="panel-list-element"><b>Telefon</b>: {$ restaurant.phone $}</span>
                        <span class="panel-list-element"><b>Promień dowozu</b>: {$ restaurant.radius $}</span>
                        <span class="panel-list-element"><b>Najtańsze danie</b>: {$ restaurant.minDishPrice $} <span
                                ng-if="!restaurant.minDishPrice">0</span> zł</span>
                    </div>
                </div>
            </a>
        </div>


    </div>

{% endblock %}

{% block includes %}
    {% include 'modals/errorModal.html' %}
{% endblock %}